[package]
name = "clapper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["cargo"] }
clap_complete = { version = "4" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
